# Generated by Django 5.0.6 on 2024-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_player_age_remove_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/static'),
        ),
        migrations.AlterField(
            model_name='player',
            name='medical_certificates',
            field=models.FileField(blank=True, null=True, upload_to='core/static'),
        ),
    ]
