# Generated by Django 5.0.6 on 2024-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_image_alter_player_medical_certificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image',
            new_name='profile_image',
        ),
    ]
