# Generated by Django 5.0.6 on 2024-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_profile_image_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='medical_certificates',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(blank=True, choices=[('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('others', 'others')], max_length=6, null=True),
        ),
    ]
