# Generated by Django 5.0.6 on 2024-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_player_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='district',
            field=models.CharField(blank=True, choices=[('Karnataka', [('Bangalore', 'Bangalore'), ('Mysore', 'Mysore'), ('Hubli', 'Hubli')]), ('Maharashtra', [('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur')]), ('Tamil Nadu', [('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai')])], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Tamil Nadu', 'Tamil Nadu'), ('others', 'others')], max_length=20, null=True),
        ),
    ]
