# Generated by Django 5.0.6 on 2024-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
