# Generated by Django 5.0.6 on 2024-07-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_player_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aadhar_card_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='player',
            name='marksheets_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/marksheets/'),
        ),
        migrations.AddField(
            model_name='player',
            name='pan_card_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
