# Generated by Django 5.0.6 on 2024-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_group_description_remove_player_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='players',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.group'),
        ),
        migrations.AlterField(
            model_name='player',
            name='relation',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('others', 'others')], max_length=40, null=True),
        ),
    ]
