# Generated by Django 5.0.6 on 2024-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_group_description_player_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
        migrations.AddField(
            model_name='player',
            name='groups',
            field=models.ManyToManyField(blank=True, to='core.group'),
        ),
    ]
